#+title: Nix on MacOS: Instructions

* Installation

** Running the downloaded binary

From [[https://nixos.org/download.html#nix-install-macos][the download
page]]:

#+begin_src sh
  sh <(curl -L https://nixos.org/nix/install)
#+end_src

The shell script downloads and runs a binary installer which will ask
you for sudo permissions. It's pretty verbose about what it's
doing. The main challenge it needs to overcome is creating a ~/nix~
directory at the root of the filesystem. On current macOS, ~/~ is
read-only, not even writeable by root. So the Nix installer needs to
create a new Apple Filesystem (APFS) volume. It also updates (in fact,
creates) ~/etc/synthetic.conf~ and ~/etc/fstab~. Finally there's a
LaunchDaemon to ensure this volume gets mounted early on during boot
up.

** Fixing shell config files

Nix needs to set your ~PATH~ and ~MANPATH~, and the Nix versions of
these need to come /before/ any other versions. The Nix installer does
this by writing to ~/etc/



* Nix

** Glossary

** Directories and configuration files

** Useful commands

